Repository EddieHubCommunity/EddieHubCommunity.github.io, pull requests merged in 2023-12, with the labels that each got.

#314 fix: overlapping of feature icon
  src/components/SecondaryFeatures.jsx
Labels: enhancement

#313 feat: improve accessibility of the project
  src/components/Header.jsx
  src/components/PrimaryFeatures.jsx
Labels: enhancement

#309 fix: Add img alt
  src/components/Newsletter.jsx
  src/components/PrimaryFeatures.jsx
  src/components/SecondaryFeatures.jsx
  src/components/Testimonials.jsx
Labels: bug

#327 docs: fix faq on how to join EddieHubCommunity github
  src/components/Faqs.jsx
Labels: documentation

#329 feat: add sitemap
  src/app/sitemap.js
Labels: enhancement
